const mongoose=require("mongoose");
const {Schema}=mongoose;
const PropertySchema = new Schema({
    'prop_id':
    {
        type:String,
        required:true
    },
    'userid':
    {
        type:String,
        required:true
    },
     'pname':{
        type:String,
        required:true
    },
    'ptype':{
        type:String,
        required:true
    },
    'availfrom':{
        type:Date,
        required:true
    },
    'rent':{
        type:Number,
        required:true
    },
    'proparea':
    {
        type:Number,
        required:true
    },
    'nobathroom':
    {
        type:Number,
        required:true
    },
    'parea':
    {
        type:String,
        required:true
    },
    'furnishing':{
        type:String,
        required:true
    },
    'maintainance':
    {
        type:String,
       
    },
    'deposit':
    {
        type:Number,
        required:true
    },
    'images':
    {
        type:Array,
        required:true
    },
    'logo':
    {
        type:String,
        required:true
    },
    'city':
    {
        type:String,
        required:true
    },
    'address':
    {
        type:String,
        required:true
    },
    'pincode':{
        type:String,
        required:true
    },
    'ptennants':{
        type:String,
       
    },
    'adtype':{
        type:String,
        required:true
    },
    'statuss':{
        type:String,
        required:true
    }

})
module.exports = mongoose.model("Propertie", PropertySchema) ; 